// <auto-generated />
using System;
using Animal_extinction.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Animal_extinction.Migrations
{
    [DbContext(typeof(TodoDBContext))]
    [Migration("20240309015436_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Animal_extinction.Model.DetailObservations", b =>
                {
                    b.Property<int>("DetailObservationsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailObservationsId"));

                    b.Property<string>("Behaviors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ObservationDate")
                        .HasColumnType("date");

                    b.Property<int>("ObservationId")
                        .HasColumnType("int");

                    b.Property<string>("ObservationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObservationsId")
                        .HasColumnType("int");

                    b.Property<string>("Ubication")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetailObservationsId");

                    b.HasIndex("ObservationsId");

                    b.ToTable("detailObservations");
                });

            modelBuilder.Entity("Animal_extinction.Model.Observations", b =>
                {
                    b.Property<int>("ObservationsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObservationsId"));

                    b.Property<int>("SpecieId")
                        .HasColumnType("int");

                    b.HasKey("ObservationsId");

                    b.HasIndex("SpecieId");

                    b.ToTable("observations");
                });

            modelBuilder.Entity("Animal_extinction.Model.Species", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpeciesId"));

                    b.Property<string>("ConservationState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSpecies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViabilityId")
                        .HasColumnType("int");

                    b.HasKey("SpeciesId");

                    b.HasIndex("ViabilityId");

                    b.ToTable("species");
                });

            modelBuilder.Entity("Animal_extinction.Model.Threats", b =>
                {
                    b.Property<int>("ThreatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThreatsId"));

                    b.Property<string>("DescriptionThreats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameThreats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThreatsLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViabilityId")
                        .HasColumnType("int");

                    b.HasKey("ThreatsId");

                    b.HasIndex("ViabilityId");

                    b.ToTable("threats");
                });

            modelBuilder.Entity("Animal_extinction.Model.Viability", b =>
                {
                    b.Property<int>("ViabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViabilityId"));

                    b.Property<string>("GeneralViability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GeneticDiversity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReproductionRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ViabilityId");

                    b.ToTable("viability");
                });

            modelBuilder.Entity("Animal_extinction.Model.DetailObservations", b =>
                {
                    b.HasOne("Animal_extinction.Model.Observations", "Observations")
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observations");
                });

            modelBuilder.Entity("Animal_extinction.Model.Observations", b =>
                {
                    b.HasOne("Animal_extinction.Model.Species", "Specie")
                        .WithMany()
                        .HasForeignKey("SpecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specie");
                });

            modelBuilder.Entity("Animal_extinction.Model.Species", b =>
                {
                    b.HasOne("Animal_extinction.Model.Viability", "Viability")
                        .WithMany()
                        .HasForeignKey("ViabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viability");
                });

            modelBuilder.Entity("Animal_extinction.Model.Threats", b =>
                {
                    b.HasOne("Animal_extinction.Model.Viability", "Viability")
                        .WithMany()
                        .HasForeignKey("ViabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viability");
                });
#pragma warning restore 612, 618
        }
    }
}
